---

  - name: Ensure the Mono GPG key has been imported
    rpm_key:
      key: "{{ sonarr_mono_gpg_key }}"
      state: present

  - name: Ensure the Mono Yum repository is present
    copy:
      src: mono.repo
      dest: /etc/yum.repos.d/mono.repo
      owner: root
      group: root
      mode: 0644

  - name: Ensure libmediainfo is installed
    package: name=libmediainfo state=present
